sps_cols <- c(`Kazachstania bulderi` = "#E2D200", `Candida parapsilosis` = "#5C82E1", 
              `Cryptococcus wingfieldii` = "#6ECEE5", `Filobasidium magnum` = "#54B4DE", 
              `Filobasidium sp` = "#CAF0B8", `Filobasidium stepposum` = "#BFECEE", 
              `Filobasidium wieringae` = "#5BB259", `Holtermanniella sp` = "#4DE8EE", 
              `Hyphopichia pseudoburtonii` = "#8CEBE9", `Naganishia sp` = "#E283B7", 
              `Saccharomyces cerevisiae` = "#DD8D29", `Aureobasidium pullulans` = "#E2C443", 
              `Clavispora lusitaniae` = "#ADD0F1", `Debaryomyces hansenii` = "#EFEEE2", 
              `Issatchenkia orientalis` = "#DD4092", `Meyerozyma caribbica` = "#59C6AA", 
              `Wickerhamomyces anomalus` = "#E8E5B1", `Candida ethanolica` = "#E27B36", 
              `Cystofilobasidium macerans` = "#7C5A8B", `Naganishia adeliensis` = "#D38E6B", 
              `Naganishia albida` = "#91BAB4", `Ascomycota sp` = "#E6A5E5", 
              `Aureobasidium sp` = "#A19DB8", `Cryptococcus sp` = "#7C8347", 
              `Cryptococcus victoriae` = "#A89CE9", `Cryptococcus wieringae` = "#D8606D", 
              `Hannaella surugaensis` = "#AD73D9", `Kazachstania humilis` = "#46ACC8", 
              `Papiliotrema flavescens` = "#DC36E7", `Pichia fermentans` = "#E559D7", 
              `Uncultured Basidiomycota` = "#EB97A4", `Bactrocera tryoni` = "#E2BF7B", 
              `Candida albicans` = "#94B637", `Trichosporon asahii` = "#5FEA42", 
              `Kazachstania unispora` = "#77A4DC", `Pichia kudriavzevii` = "#665CDF", 
              `Pichia sporocuriosa` = "#65F2D8", `Rhodotorula mucilaginosa` = "#C0E9D1", 
              `Saccharomyces sp` = "#BEC4C3", `Pichia heedii` = "#E0AEBF", 
              `Triticum aestivum` = "#E6C5B0", `Candida intermedia` = "#9FE9A0", 
              `Candida sp` = "#54E8AE", `Candida tropicalis` = "#D9BFEF", `Kazachstania sp` = "#E4A54E", 
              `Uncultured Ascomycota` = "#BCEF7E", `Colletogloeum sp` = "#E5EF3A", 
              `Rhodotorula sp` = "#A7978F", `Saturnispora silvae` = "#50AFB2", 
              `Wickerhamomyces sp` = "#5C5E66", `Cryptococcus flavescens` = "#E2E66E", 
              `Holtermanniella festucosa` = "#429F6E", `Holtermanniella takashimae` = "#79E05E", 
              `Sporobolomyces sp` = "#A7B98C", `Tremellomycetes sp` = "#62EB88", 
              `Wickerhamiella pararugosa` = "#94E8BE", `Cryptococcus adeliensis` = "#B1ED42", 
              `Filobasidium oeirense` = "#D6E390", `Kwoniella heveanensis` = "#8838EA", 
              `Torulaspora delbrueckii` = "#E5D4E8")